# Generated by Django 4.2.2 on 2023-06-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_data_alter_task_max_deadlines_alter_task_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="collected",
            field=models.IntegerField(),
        ),
    ]
