# Generated by Django 4.2.2 on 2023-06-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_remove_data_finish_button_pressed"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="finish_button_pressed",
            field=models.BooleanField(default=False),
        ),
    ]
