# Generated by Django 4.2.2 on 2023-06-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_data_finish_button_pressed"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskToAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_id", models.IntegerField()),
                ("deadline_date", models.DateField()),
                ("deadline_time", models.TimeField()),
                ("progress", models.IntegerField()),
            ],
        ),
    ]
