# Generated by Django 4.2.2 on 2023-06-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0002_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_task", models.CharField(max_length=255)),
                ("field_size", models.CharField(max_length=255)),
                ("max_deadlines", models.IntegerField()),
            ],
        ),
    ]
