# Generated by Django 4.2.2 on 2023-06-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collected", models.CharField(max_length=255)),
                ("add_file", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "data",
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="max_deadlines",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name="task",
            table="tasks",
        ),
    ]
