# Generated by Django 4.2.2 on 2023-06-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_data_collected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="collected",
            field=models.CharField(max_length=255),
        ),
    ]
