# Generated by Django 4.2.2 on 2023-06-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_data_collected"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="finish_button_pressed",
            field=models.BooleanField(default=False),
        ),
    ]
