# Generated by Django 4.2.2 on 2023-06-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_data_finish_button_pressed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="finish_button_pressed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
