# Generated by Django 4.2.2 on 2023-06-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_data_finish_button_pressed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="finish_button_pressed",
        ),
    ]
