# Generated by Django 4.2.2 on 2023-06-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_tasktoauthor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasktoauthor",
            name="deadline_time",
        ),
    ]
